workflows:
  wcdonalds:
    name: Build for iOS
    instance_type: mac_mini
    max_build_duration: 60
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Build for iOS
        script: flutter build ios
    artifacts:
      - build/**/outputs/bundle/**/*.aab