name: wcdonalds_app
description: The best fast food enterprise and burgas flippers of all the metaverse.

publish_to: 'none' 

version: 0.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  http: ^0.13.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.0
  package_info_plus: ^1.4.0
  flutter_staggered_grid_view: ^0.6.1
  transparent_image: ^2.0.0
  go_router: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/logo_y.png
    - assets/images/logo_w.png
    - assets/images/worker_w.png
    - assets/images/welcome.png
    - assets/images/wcdonalds.png
    - assets/images/wcdollar.png
    - assets/images/faq.png
    - assets/images/franchise_1.jpeg
    - assets/images/franchise_2.jpeg
    - assets/data/rarity.json
    
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  